# Generated by Django 5.2.8 on 2025-11-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
